### ISSUE TITLE
Signed Bootstrap Package

### ISSUE THREAD

**Issue by nixtar** [macadmins/munki-builds#14]
Hey,

Thanks for making these builds available, we have switched to using these instead of building and signing our own builds. ❤️

We are looking at deploying Munki with our MDM during ADE and are interested in using a bootstrapped installer.
What are the chances we could start getting signed bootstraped installers (make_munki_mpkg.sh with -B switch)?

Thanks,
Nick

**Comment by gregneagle** [comment]
Are you sure that will work for you? Normally during ADE, you also go through Apple's Setup Assistant and create a local account. After Setup Assistant exits, the machine is automatically logged into the account that was just created, and so the machine is never at the loginwindow and bootstrap won't occur until the next logout or reboot.

It's precisely complexity like this that means there are at least three widely useful permutations of the pkg:

1) One without anything that triggers bootstrapping or a background run. Especially useful for upgrading existing installs.
2) One with bootstrapping enabled when the tools will be installed at the loginwindow, or you know the machine will be at the loginwindow soon after install. This was especially useful back when we all did "imaging" as then Munki would run on the first boot.
3) One with a script to trigger a background run immediately after install (make_munki_mpkg.sh with the -A option). This is useful in the above ADE/DEP scenario.

The real fundamental problem here is that it's difficult/unreliable to install multiple packages via MDM during ADE/DEP, if this was reliable, you'd just install the munkitools pkg and an additional package to set up bootstrapping or trigger a background run, or whatever additional things you need. File Feedback with Apple!

**Comment by nixtar** [comment]
Excellent points as usual Greg. 👍

Yes -A is probably more appropriate for what I was trying to do, but there is also a race condition as our MDM (intune) installs apps before configuration profiles so munki will be installed before it's configured.

Back to the drawing board on my end.
